blog/urls.py
from django.conf.urls import url
from . import views
from haystack.views import SearchView
from .forms import DateRangeSearchForm

app_name = 'blog'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^register/$', views.register, name='register'),
    url(r'^list/$', views.ListView.as_view(), name='list'),
    url(r'^drafts/$', views.DraftView.as_view(), name='drafts'),
    url(r'^article/(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^article/new/$', views.post_new, name='new_post'),
    url(r'^article/(?P<pk>[0-9]+)/edit/$', views.post_edit, name='post_edit'),
    url(r'^article/(?P<pk>[0-9]+)/publish/$', views.post_pub, name='post_pub'),
    url(r'^article/(?P<pk>[0-9]+)/remove/$', views.post_remove, name='post_remove'),
    url(r'^article/img_upload', views.img_upload, name='img_upload'),
    url(r'^article/search', SearchView(form_class=DateRangeSearchForm), name='post_search'),
    url(r'^article/(?P<pk>[0-9]+)/addComment', views.add_comment, name='add_comment'),
]

mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth import views as auth_views

urlpatterns = [
    url(r'^polls/', include('polls.urls')),
    url(r'', include('blog.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^', include('django.contrib.auth.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

polls/urls.py
from django.conf.urls import url
from . import views

app_name = 'polls'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^(?P<pk>[0-9]+)/results/$', views.ResultsView.as_view(), name='results'),
    url(r'^(?P<question_id>[0-9]+)/votes/$', views.vote, name='vote'),
]

polls/models.py
import datetime
from django.db import models
from django.utils import timezone


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    des_img = models.ImageField(upload_to='polls/uploads/', blank=True)

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        return timezone.now() >= self.pub_date >= timezone.now() - datetime.timedelta(days=1)

    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published Recently?'


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

polls/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views import generic
from django.utils import timezone
from .models import Choice, Question


class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        return Question.objects.filter(pub_date__lte=timezone.now()).order_by('-pub_date')[:5]


class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'

    def get_queryset(self):
        return Question.objects.filter(pub_date__lte=timezone.now())


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'

    def get_queryset(self):
        return Question.objects.filter(pub_date__lte=timezone.now())


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

polls/templates/polls/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}base page{% endblock %}</title>
    {% load staticfiles %}
    <link  href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" />
    <link  href="{% static 'css/style.css' %}" rel="stylesheet" />
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    {% block otherlink %}{% endblock %}
</head>
<body>
    <nav class="navbar navbar-default">
        <div class="container">
            <div class="navbar-header">
                <a class="navbar-brand" href="{% url 'blog:index' %}">Erlie&apos;s Blog</a>
            </div>
            <div>
                <ul class="nav navbar-nav">
                    <li><a href="{% url 'blog:index' %}">Index</a></li>
                    <li><a href="{% url 'blog:list' %}">Blog List</a></li>
                    <li><a href="{% url 'blog:drafts' %}">Drafts</a></li>
                    <li><a href="{% url 'polls:index' %}">Polls</a></li>
                </ul>
                {% if user.is_authenticated %}
                    <a href="{% url 'blog:new_post' %}">
                        <button type="button" class="btn btn-primary navbar-btn navbar-right">New Post</button>
                    </a>
                    <p class="navbar-text navbar-right" id="nav-login-info">Hello, {{ user.username }}.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href="{% url 'logout' %}">Log out</a></p>
                {% else %}
                    <p class="navbar-text navbar-right" id="nav-login-info">Welcome, new user.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Please <a href="{% url 'login' %}">Sign in</a> or <a href="{% url 'blog:register' %}">Sign up</a></p>
                {% endif %}
                <form class="navbar-form navbar-right" action="{% url 'blog:post_search' %}" role="search" method="get">
                    <div class="form-group">
                        <input type="text" class="form-control" name="q" placeholder="Search">
                    </div>
                    <button type="submit" class="btn btn-default"><span class="glyphicon glyphicon-search"></span></button>
                </form>
            </div>
        </div>
    </nav>
    <div class="container">
    {% block content %}{% endblock %}
    </div>

</body>
</html>

polls/templates/polls/detail.html
{% extends 'polls/base.html' %}

{% block title %} {{ question.question_text }} {% endblock %}

{% block content %}
    <h1>{{ question.question_text }}</h1>
    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
    <img src="{{ question.des_img.url }}" alt="Question Description">
    <form action="{%  url 'polls:vote' question.id %}" method="post">
        {% csrf_token %}
        {% for choice in question.choice_set.all %}
            <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
            <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />
        {% endfor %}
        <input type="submit" value="Vote"} />
    </form>
{% endblock %}

polls/templates/polls/index.html
{% extends 'polls/base.html' %}

{% block title %}Polls list -- Erlie's Blog{% endblock %}

{% block content %}
    {%  if latest_question_list %}
        <ul>
            {% for question in latest_question_list %}
                <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a> date: {{ question.pub_date }}</li>
            {% endfor %}
        </ul>
    {% else %}
        <p>No polls are available.</p>
    {% endif %}
{% endblock %}

polls/templates/polls/results.html
{% extends 'polls/base.html' %}

{% block title %}Results of {{ question.question_text }} -- Erlie's Blog{% endblock %}

{% block content %}
    <h1>{{ question.question_text }}</h1>
    <ul>
        {% for choice in question.choice_set.all %}
            <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes | pluralize }}</li>
        {% endfor %}
    </ul>

    <a href="{% url 'polls:detail' question.id %}">Vote again?</a>
{% endblock %}