blog/urls.py
from django.conf.urls import url
from . import views
from haystack.views import SearchView
from .forms import DateRangeSearchForm

app_name = 'blog'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^register/$', views.register, name='register'),
    url(r'^list/$', views.ListView.as_view(), name='list'),
    url(r'^drafts/$', views.DraftView.as_view(), name='drafts'),
    url(r'^article/(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^article/new/$', views.post_new, name='new_post'),
    url(r'^article/(?P<pk>[0-9]+)/edit/$', views.post_edit, name='post_edit'),
    url(r'^article/(?P<pk>[0-9]+)/publish/$', views.post_pub, name='post_pub'),
    url(r'^article/(?P<pk>[0-9]+)/remove/$', views.post_remove, name='post_remove'),
    url(r'^article/img_upload', views.img_upload, name='img_upload'),
    url(r'^article/search', SearchView(form_class=DateRangeSearchForm), name='post_search'),
    url(r'^article/(?P<pk>[0-9]+)/addComment', views.add_comment, name='add_comment'),
]

mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth import views as auth_views

urlpatterns = [
    url(r'^polls/', include('polls.urls')),
    url(r'', include('blog.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^', include('django.contrib.auth.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

polls/urls.py
from django.conf.urls import url
from . import views

app_name = 'polls'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^(?P<pk>[0-9]+)/results/$', views.ResultsView.as_view(), name='results'),
    url(r'^(?P<question_id>[0-9]+)/votes/$', views.vote, name='vote'),
]

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse


class BlogUser(models.Model):
    user = models.OneToOneField(User)
    avatar = models.ImageField(upload_to='blog/upload/avatar', blank=True)
    date_of_birth = models.DateField(verbose_name='Date of Birth', blank=True)


class Post(models.Model):
    author = models.ForeignKey(User)
    title = models.CharField(max_length=200)
    text = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)
    pub_date = models.DateTimeField(blank=True, null=True)

    def publish(self):
        self.pub_date = timezone.now()
        self.save()

    def save_draft(self):
        self.created_date = timezone.now()
        self.save()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:detail', kwargs={'pk': self.pk})


class ImageInPost(models.Model):
    image = models.ImageField(upload_to='blog/upload/image')


class Comment(models.Model):
    author = models.ForeignKey(User)
    bound_to_post = models.ForeignKey(Post)
    floor = models.IntegerField(default=1)
    content = models.TextField()
    date = models.DateTimeField(default=timezone.now)

    class Meta:
        ordering = ['-date']

    def __str__(self):
        return self.content

blog/forms.py
from django.forms import modelform_factory
from .models import Post, Comment
from django import forms
from haystack.forms import SearchForm


PostForm = modelform_factory(Post, fields=("title", "text"))

CommentForm = modelform_factory(Comment, fields=("content",))


class RegisterForm(forms.Form):
    username = forms.CharField(label='Username', max_length=150)
    password = forms.CharField(label='Password', min_length=8, max_length=100, widget=forms.PasswordInput)
    email = forms.EmailField(label='Email')
    date_of_birth = forms.DateField(label='DateOfBirth')
    avatar = forms.ImageField(label='Avatar', required=False)


class DateRangeSearchForm(SearchForm):
    start_date = forms.DateField(required=False)
    end_date = forms.DateField(required=False)

    def search(self):
        sqs = super(DateRangeSearchForm, self).search()
        if not self.is_valid():
            return self.no_query_found()

        if self.cleaned_data['start_date']:
            sqs = sqs.filter(pub_date__gte=self.cleaned_data['start_date'])

        if self.cleaned_data['end_date']:
            sqs = sqs.filter(pub_date__lte=self.cleaned_data['end_date'])

        return sqs

blog/views.py
from django.views import generic
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from .models import Post, ImageInPost, Comment, BlogUser
from django.utils import timezone
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse, reverse_lazy
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from .forms import PostForm, CommentForm, RegisterForm
from django.conf import settings
from haystack.forms import SearchForm


class IndexView(generic.ListView):
    template_name = 'blog/index.html'
    context_object_name = 'latest_post_list'

    def get_queryset(self):
        return Post.objects.filter(pub_date__isnull=False).order_by('-pub_date')[:5]


class ListView(generic.ListView):
    template_name = 'blog/list.html'
    context_object_name = 'post_list'
    paginate_by = 10

    def get_queryset(self):
        return Post.objects.filter(pub_date__isnull=False).order_by('-pub_date')


class DraftView(generic.ListView):
    template_name = 'blog/drafts.html'
    context_object_name = 'draft_list'

    def get_queryset(self):
        return Post.objects.filter(pub_date__isnull=True).order_by('-created_date')


class DetailView(generic.DetailView):
    model = Post
    template_name = 'blog/detail.html'

    def get_context_data(self, **kwargs):
        context = super(DetailView, self).get_context_data(**kwargs)
        form = CommentForm()
        context['comment_form'] = form
        return context


@login_required
def post_new(request):
    if request.method == "POST":
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            if request.POST.get('operation') == 'publish':
                post.publish()
            else:
                post.save_draft()
            return redirect('blog:detail', pk=post.pk)
    else:
        form = PostForm()
    return render(request, 'blog/post_edit.html', {'form': form})


def register(request):
    if request.user.is_authenticated:
        return redirect('blog:index')
    if request.method == "POST":
        form = RegisterForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            email = form.cleaned_data['email']
            original_user = User.objects.create_user(username, email, password)
            original_user.save()
            date_of_birth = form.cleaned_data['date_of_birth']
            instance = BlogUser()
            if 'avatar' in request.FILES:
                instance.avatar = request.FILES['avatar']
                if not validate_filename(instance.avatar.name):
                    instance = BlogUser()
            else:
                instance = BlogUser()
            instance.date_of_birth = date_of_birth
            instance.user = original_user
            instance.save()
            return redirect('login')
    else:
        form = RegisterForm()
    return render(request, 'blog/register.html', {'form': form})


@login_required
def post_edit(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.method == "POST":
        form = PostForm(request.POST, instance=post)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.publish()
            return redirect('blog:detail', pk=post.pk)
    else:
        form = PostForm(instance=post)
    return render(request, 'blog/post_edit.html', {'form': form, 'post': post})


@login_required
def post_pub(request, pk):
    post = get_object_or_404(Post, pk=pk)
    post.publish()
    return redirect('blog:detail', pk=post.pk)


@login_required
def post_remove(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.method == "POST":
        if request.POST.get('operation') == 'Confirm':
            post.delete()
            return redirect('blog:list')
        else:
            return redirect('blog:detail', pk=post.pk)
    return render(request, 'blog/remove.html', {'post': post})


@login_required
def add_comment(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.author = request.user
            comment.floor = Comment.objects.all().count() + 1
            comment.bound_to_post = post
            comment.save()
    return redirect('blog:detail', pk=post.pk)


def img_upload(request):
    if request.method == 'POST':
        instance = ImageInPost(image=request.FILES['ImgName'])
        if validate_filename(instance.image.name):
            instance.save()
            return HttpResponse(instance.image.url, content_type="text/html", charset="utf-8")
        else:
            return HttpResponse("error| invalid extension", content_type="text/html", charset="utf-8")
    else:
        return HttpResponse("error| upload failed", content_type="text/html", charset="utf-8")


def validate_filename(filename):
    ALLOWED_EXTENSIONS = set(['png', 'jpg', 'jpeg', 'gif'])
    return '.' in filename and filename.rsplit('.', 1)[1] in ALLOWED_EXTENSIONS

blog/templates/blog/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}base page{% endblock %}</title>
    {% load staticfiles %}
    <link  href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" />
    <link  href="{% static 'css/style.css' %}" rel="stylesheet" />
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    {% block otherlink %}{% endblock %}
</head>
<body>
    <nav class="navbar navbar-default">
        <div class="container">
            <div class="navbar-header">
                <a class="navbar-brand" href="{% url 'blog:index' %}">Erlie&apos;s Blog</a>
            </div>
            <div>
                <ul class="nav navbar-nav">
                    <li><a href="{% url 'blog:index' %}">Index</a></li>
                    <li><a href="{% url 'blog:list' %}">Blog List</a></li>
                    <li><a href="{% url 'blog:drafts' %}">Drafts</a></li>
                    <li><a href="{% url 'polls:index' %}">Polls</a></li>
                </ul>
                {% if user.is_authenticated %}
                    <a href="{% url 'blog:new_post' %}">
                        <button type="button" class="btn btn-primary navbar-btn navbar-right">New Post</button>
                    </a>
                    <p class="navbar-text navbar-right" id="nav-login-info">Hello, {{ user.username }}.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href="{% url 'logout' %}">Log out</a></p>
                {% else %}
                    <p class="navbar-text navbar-right" id="nav-login-info">Welcome, new user.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Please <a href="{% url 'login' %}">Sign in</a> or <a href="{% url 'blog:register' %}">Sign up</a></p>
                {% endif %}
                <form class="navbar-form navbar-right" action="{% url 'blog:post_search' %}" role="search" method="get">
                    <div class="form-group">
                        <input type="text" class="form-control" name="q" placeholder="Search">
                    </div>
                    <button type="submit" class="btn btn-default"><span class="glyphicon glyphicon-search"></span></button>
                </form>
            </div>
        </div>
    </nav>
    <div class="container">
    {% block content %}{% endblock %}
    </div>

</body>
</html>

blog/templates/blog/detail.html
{% extends 'blog/base.html' %}

{% block title %}{{ post.title }}--Erlie's Blog{% endblock %}

{% block otherlink %}
    <script>
        $(document).ready(function () {
           $("#id_content").addClass("form-control").attr("placeholder", "Type your comment...");
        });
    </script>
{% endblock %}

{% block content %}
    {%  if post %}
        <h1>{{ post.title }}</h1>
        <div class="row">
            <div class="col-sm-2 text-left">
                <h4 class="text-muted">Author: {{ post.author.username }}</h4>
            </div>
            <div class="col-sm-4">
                {% if post.pub_date %}
                    <h4 class="text-muted">Published Date: {{ post.pub_date|date:"H:i M d, Y" }}</h4>
                {% else %}
                    <h4 class="text-muted">Created Date: {{ post.created_date|date:"H:i M d, Y" }}</h4>
                {% endif %}
            </div>
            <div class="col-sm-6 text-right">
            {% if post.pub_date is None %}
                <a href="{% url 'blog:post_pub' post.id%}"><button type="button" class="btn btn-primary">Publish</button></a>
            {% endif %}
                <a href="{% url 'blog:post_edit' post.id%}"><button type="button" class="btn btn-warning">Edit</button></a>
                <a href="{% url 'blog:post_remove' post.id%}"><button type="button" class="btn btn-danger">Delete</button></a>
            </div>
            <div id="detail-text" class="col-sm-12">{{ post.text|safe }}</div>
        </div>
        {% for comment in post.comment_set.all %}
            <div class="media">

            </div>
        {% empty %}
            <p class="text-muted lead">No comments now! Comment for Sofa!</p>
        {% endfor %}

        <form method="POST" action="{% url 'blog:add_comment' post.id %}" role="form">
            {% csrf_token %}
            <div class="form-group">
                <label>Post a comment:</label>
                {{ comment_form.content }}
            </div>
            <button type="submit" class="btn btn-default pull-right">Commit</button>
        </form>

    {% else %}
        <p>Article Not Found!</p>
    {% endif %}
{% endblock %}

blog/templates/blog/drafts.html
{% extends "blog/base.html" %}

{% block title %}Drafts--Erlie's Blog{% endblock %}

{% block content %}
    {% if draft_list %}
        <table class="table table-hover" id="blog-list">
            <caption><h1>Drafts List</h1></caption>
            <thead><tr><th>Title</th><th>Created Date</th></tr></thead>
            <tbody>
            {% for post in draft_list %}
                <tr>
                    <td><a href="{% url 'blog:detail' post.id %}">{{ post.title|capfirst }}</a></td>
                    <td class="text-muted">{{ post.created_date|date:"H:i M d, Y" }}</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    {% else %}
        <p>No posts are available.</p>
    {% endif %}
{% endblock %}

blog/templates/blog/index.html
{% extends "blog/base.html" %}

{% block title %}Index--Erlie's Blog{% endblock %}

{% block content %}
    <h1 id="index-title">The Recent Blog:</h1>
    {%  if latest_post_list %}
        <ul id="index-recent">
            {% for post in latest_post_list %}
                <li>
                    <div class="row">
                        <div class="col-sm-6 text-left">
                            <h2><a href="{% url 'blog:detail' post.id %}">{{ post.title|capfirst }}</a></h2>
                        </div>
                        <div class="col-sm-6 text-right text-muted"><h4>Publish Date: {{ post.pub_date|date:"H:i M d, Y" }}</h4></div>
                        <div class="col-sm-12"><p>{{ post.text|striptags|truncatechars:500 }}</p></div>
                    </div>
                </li>
            {% endfor %}
        </ul>
    {% else %}
        <p>No posts are available.</p>
    {% endif %}
{% endblock %}

blog/templates/blog/list.html
{% extends "blog/base.html" %}

{% block title %}List--Erlie's Blog{% endblock %}

{% block content %}
    {% if post_list %}
        <table class="table table-hover" id="blog-list">
            <caption><h1>Blog List</h1></caption>
            <thead><tr><th>Title</th><th>Publish Date</th></tr></thead>
            <tbody>
            {% for post in post_list %}
                <tr>
                    <td><a href="{% url 'blog:detail' post.id %}">{{ post.title|capfirst }}</a></td>
                    <td class="text-muted">{{ post.pub_date|date:"H:i M d, Y" }}</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
        <div class="text-center">
            <ul class="pagination">
                {% if page_obj.has_previous %}
                    <li><a href="?page={{ page_obj.previous_page_number }}">&laquo;</a></li>
                {% else %}
                    <li class="disabled"><a href="#">&laquo;</a></li>
                {% endif %}
                {% for i in page_obj.paginator.page_range %}
                    <li {% if i == page_obj.number %} class="active" {% endif %}><a href="?page={{ i }}">{{ i }}</a></li>
                {% endfor %}
                {% if page_obj.has_next %}
                    <li><a href="?page={{ page_obj.next_page_number }}">&raquo;</a></li>
                {% else %}
                    <li class="disabled"><a href="#">&raquo;</a></li>
                {% endif %}
            </ul>
        </div>
    {% else %}
        <p>No posts are available.</p>
    {% endif %}
{% endblock %}

blog/templates/blog/post_edit.html
{% extends 'blog/base.html' %}

{% block title %}
    {% if post %}
        {{ post.title }}
    {% else %}
        New Post
    {% endif %}
{% endblock %}

{% block otherlink %}
    {% load staticfiles %}
    <link rel="stylesheet" href="{% static 'wangEditor/css/wangEditor.min.css' %}" />
    <script src="{% static 'wangEditor/js/wangEditor.min.js' %}"></script>
    <script>
        function getCookie(name) {
            var cookieValue = null;
            if (document.cookie && document.cookie !== '') {
                var cookies = document.cookie.split(';');
                for (var i = 0; i < cookies.length; i++) {
                    var cookie = jQuery.trim(cookies[i]);
                    // Does this cookie string begin with the name we want?
                    if (cookie.substring(0, name.length + 1) === (name + '=')) {
                        cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                        break;
                    }
                }
            }
            return cookieValue;
        }
    </script>
{% endblock %}

{% block content %}
    <div id="post-edit">
        {% if post %}
            <h1>{{ post.title }}</h1>
        {% else %}
            <h1>New Post</h1>
        {% endif %}
        <form method="POST">
        {% csrf_token %}
            <p id="post-edit-title">
                {{ form.title.label_tag }}
                {{ form.title }}
            </p>
            <p id="post-edit-text">
                {{ form.text }}
            </p>
            <button type="submit" class="btn btn-primary" name="operation" value="publish">Publish</button>
            {% if post.pub_date is None%}
                <button type="submit" class="btn btn-default" name="operation" value="save">Save</button>
            {% endif %}
            <a href="{% if post %} {% url 'blog:detail' post.id %} {% else %} {% url 'blog:index' %} {% endif %}"><input type="button" class="btn btn-warning" value="Cancel" /></a>
        </form>
    </div>
    <script>
        var textarea = document.getElementById('id_text');
        var editor = new wangEditor(textarea);
        editor.config.lang = wangEditor.langs['en'];
        editor.config.uploadImgFileName = 'ImgName';
        editor.config.uploadImgUrl = '{% url 'blog:img_upload' %}';
        var token = getCookie('csrftoken');
        editor.config.uploadHeaders = {
            'X-CSRFToken' : token
        };
        editor.create()
    </script>
{% endblock %}

blog/templates/blog/register.html
{% extends 'blog/base.html' %}

{% block title %}Register{% endblock %}

{% block otherlink %}
    <script>
        $(document).ready(function () {
            $("#register-form input").addClass("form-control");
            $("#register-form label").addClass("control-label col-sm-4");
        });
    </script>
{% endblock %}

{% block content %}
    <div class="row"><div class="col-sm-4 col-sm-push-4">
        <form enctype="multipart/form-data" method="post" role="form" class="form-horizontal" id="register-form">
            {% csrf_token %}
            {% for field in form %}
                <div class="form-group">
                    {{ field.errors }}
                    {{ field.label_tag }}
                    <div class="col-sm-8">
                        {{ field }}
                    </div>
                </div>
            {% endfor %}

            <div class="text-right"><button type="submit" class="btn btn-success">Submit</button></div>
        </form>
    </div></div>
{% endblock %}

blog/templates/blog/remove.html
{% extends 'blog/base.html' %}

{% block title %}Sure to Remove?{% endblock %}

{% block content %}
    <div id="remove-dialog">
        <h4 class="text-center">Sure to remove {{ post.title }}?</h4>
        <form action="{% url 'blog:post_remove' post.id %}" method="post" class="text-center">
            {% csrf_token %}
            <input type="submit" class="btn btn-default" name="operation" value="Cancel" />
            <input type="submit" class="btn btn-danger" name="operation" value="Confirm" />
        </form>
    </div>
{% endblock %}